set -g mode-keys vi
set -g mouse on
set-option -g set-clipboard on

bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "pbcopy"

#set -g status-position top
set -g status-style fg=colour250,bg=colour234
set -g status-left-length 30
set -g status-right-length 80

set -g status-left "#[bold]#S #[default]"
set -g status-right "#(~/.tmux-status.sh) %Y-%m-%d %H:%M"

set -g window-status-format " #I:#W "
set -g window-status-current-format " #I:#W "
set -g window-status-current-style fg=colour234,bg=colour81,bold

set -g pane-active-border-style fg=colour81
set -g pane-border-style fg=colour238
